### ISSUE TITLE
A description of your academic note workflow

### ISSUE THREAD

**Issue by jimmerricks** [bdarcus/.doom.d#1]
My apologies that this is a quite broad request, but I am very interested in how you are using Emacs. Could describe your academic note workflow in more detail?

My use case is very similar to yours. I am a sociology postdoc looking to integrate zettelkasten-style content notes with bibliographic notes using Doom + `org-roam` + `org-roam-bibtex`. I have a 6000+ reference library that I'm managing in Zotero (and exporting with Better BibTex), and am not ready to go fullbore `org-ref` just yet. Getting everything working together is a bit of a spit and duct tape job, which is not helped by my being new to Emacs.

More specifically: How do you insert a citation in an org file? Are you using org-style citations or pandoc markdown or something else (are you project files consistent with notes in this respect)? How do you usually create a new reference note? Are you using `org-ref` to move from a citation to its note (as in the `org-roam-bibtex` demo video)? Does this require you to load both `ivy` and `helm` in an `org-roam` note buffer?

**Comment by bdarcus** [comment]
Most of my current writing projects are in pandoc markdown.

So I use that in org also, currently.

When org integrates native citation support, I expect to move to that.

I use ivy-bibtex for citation insertion.

I normally open the note from the bib entry, typically using ivy-bibtex.

**Comment by bdarcus** [comment]
Suffice to a lot has changed in a few years. Basically, the `vertico` + `biblio` + `org +roam2` init options should get you a nicely integrated setup centered on `citar`.
