### ISSUE TITLE
Obsolete functions

### ISSUE THREAD

**Issue by asymmetric** [bdarcus/.doom.d#2]
Hi!

I noticed your config uses some obsolete functions, like `citar-open-pdf` [here](https://github.com/bdarcus/.doom.d/blob/39f1c2c49b80f5f2995df1e51270a57fa76556d0/bindings.el#L12).

Are you still using this config? Asking so that I know if it makes sense to use it as reference :)

**Comment by bdarcus** [comment]
I do still use it (though need to rewrite it all), but that map doesn't
actually work for me, so I didn't notice the problem.

If you can figure out how to fix it, we can fix both issues!

**Comment by bdarcus** [comment]
FIxed the bug.
